server:
  port: 8080

spring:
  profiles:
    include: secret
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

image:
  upload:
    path: /Users/wook/upload/article-images


