server:
  port: 8080

spring:
  profiles:
    include: secret
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}

image:
  upload:
    path: src/main/upload/article-images


